<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="NextMinorStep" Id="{70ffbba5-aa46-4222-be25-7aac3270a8dc}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION NextMinorStep : UDINT
VAR_INPUT
	StateVar	: UDINT;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[NextMinorStep := StateVar + 1;]]></ST>
    </Implementation>
    <LineIds Name="NextMinorStep">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>